StructType(
    List(
        StructField('hvfhs_license_num',StringType,True),
        StructField('dispatching_base_num',StringType,True),
        StructField('pickup_datetime',TimeStampType,True),
        StructField('dropoff_datetime',TimeStampType,True),
        StructField('PULocationID',IntegerType,True),
        StructField('DOLocationID',IntegerType,True),
        StructField('SR_Flag',StringType,True)
        )
    )